### ISSUE TITLE
Execute GitHub actions on self-hosted worker

### ISSUE THREAD

**Issue by UnicycleUnicorn** [YCP-Rev-Metrix/Cloud-Infrastructure#28]
Consider using a mini. We may move to Digital Ocean in the future.

**Comment by vickSapien** [comment]
Have a mini setup in the capstone Room, as a self-hosted runner. Able to finish a workflow [link to successful run](https://github.com/vickEretus/Cloud-Nuget/actions/runs/6869401428)
