### ISSUE TITLE
Cloud testing on local Mini

### ISSUE THREAD

**Issue by vickSapien** [YCP-Rev-Metrix/Cloud-Infrastructure#3]
Setup API on a local machine to act as if in the cloud 

- Server on mini
- Database's on a separate mini
- Client implemented in mobile app 
- TLS encryption on API communication

**Comment by robertwood68** [comment]
This is being scrapped due to local network issues -- instead we'll be using my droplet for minimal comms testing then if all falls into place we will work on migrating the API and DB's to the "School's" droplet (Dr. B's)
